info:
  component: Resource Registry Management

spring:
  application:
    name: resource-registry-management
  data:
    mongodb:
#      # Setting for local instance of MongoDB
#      host: localhost
#      port: 29017
#      database: resource_registry_db

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 17100
  error:
    include-message: always

logging:
  file:
    name: logs/${spring.application.name}/spring-boot.log